{{- define "eric-enmsg-fileaccountservice.serviceLbIPv4TCP" -}}
metadata:
  name: fileaccountservice-ipv4-tcp
spec:
  loadBalancerIP: {{ .Values.global.vips.svc_CM_vip_ipaddress }}
  selector:
    app: fileaccountservice
{{- end}}
{{- if and .Values.global.loadBalancerSVC.enabled .Values.global.ip_version (or (eq .Values.global.ip_version "Dual") (eq .Values.global.ip_version "IPv4")) }}
{{- template "eric-enm-common-helmchart-library.serviceLbIPv4TCP" (list . "eric-enmsg-fileaccountservice.serviceLbIPv4TCP") -}}
{{- end }}