{{- define "eric-enmsg-fileaccountservice.serviceLbIPv6TCP" -}}
metadata:
  name: fileaccountservice-ipv6-tcp
spec:
  loadBalancerIP: {{ .Values.global.vips.svc_CM_vip_ipv6address }}
  selector:
    app: fileaccountservice
{{- end}}
{{- if and .Values.global.loadBalancerSVC.enabled .Values.global.ip_version (or (eq .Values.global.ip_version "Dual") (eq .Values.global.ip_version "IPv6_EXT")) }}
{{- template "eric-enm-common-helmchart-library.serviceLbIPv6TCP" (list . "eric-enmsg-fileaccountservice.serviceLbIPv6TCP") -}}
{{- end }}